server:
  port: 8081
  servlet:
    context-path: /crud
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/crud_example"
    username: root
    password: giang63ptit
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true